### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by kain88-de**
This removes some old cruft and adds new tests. The division test is still failing under python3 I'll check tomorrow what the reason might be.

Also I saw that you have several additions defined. A normal one and a special per grid point one. But since we use numpy they are the same in the current implementation. Care if I remove them?

btw this brings coverage to 50%

### CODE REVIEW

**Comment by kain88-de** [comment]
It was late yesterday. I would remove the `__r<op>__` functions. I'm also working a little bit to get the coverage score of at least `core.py` a little bit higher

**Comment by kain88-de** [comment]
> It was late yesterday. I would remove the __r<op>__ functions.

nevermind. a quick google search explained what these operator are for. I'm testing them as well now.

**Comment by richardjgowers** [comment]
Cool, if you've added travis in you should also put up the badges for this [like here](https://raw.githubusercontent.com/MDAnalysis/mdanalysis/develop/README.rst)

**Comment by kain88-de** [comment]
OK this is now testing a lot of the grid object. I haven't added test's for the file formats a lot. This is because I think all of them should be refactored to be simpler and best follow a simple API, especially the openDX file. Expect for the interpolation algorithm all the math stuff in the Grid object should be tested now.

I also refactored the code a little bit to make testing easier and be sure to get the math right.
Could have been I fixed a bug or two with that.

**Pull request merged**
