### PR TITLE
Add conda badge

### PR DESCRIPTION
**Pull request by kain88-de**
Let people now they can install this package with conda.

### CODE REVIEW

**Comment by kain88-de** [comment]
we can also have a badge that just shows the latest available version in anaconda.

https://anaconda.org/MDAnalysis/griddataformats/badges

**Comment by kain88-de** [comment]
@MDAnalysis/coredevs anybody a idea why this suddenly fails on travis with missing libgfortran libraries?

It worked about an hour ago.

**Comment by orbeckst** [comment]
On 3 Mar, 2016, at 16:00, kain88-de wrote:

> @MDAnalysis/coredevs anybody a idea why this suddenly fails on travis with missing libgfortran libraries?
> 
> It worked about an hour ago.

Without looking: usually conda's fault, maybe they updated something again. There are older issues both for MDA and gridDataFormats on what we did in the past (mainly pinning certain versions and not using the MKL build, IIRC).

(Sorry to not be more helpful but don't have time to go digging right now.)

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
Yes they updated libgfortran. I'll check it out with my conda installation on the laptop.

**Comment by kain88-de** [comment]
@orbeckst thanks. I needed to remove the pin for the old scipy version. The libgfortran that one linked against isn't available on conda anymore.

**Pull request merged**
