### PR TITLE
Update deploy for OIDC credentials

### PR DESCRIPTION
**Pull request by IAlibay**
It's been a long day, I hope that I've changed all the references from mda-xdrlib to GridDataFormats properly!

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
Does this now run in a *deploy* environment?

Do we have to configure this environment in the repo settings? Presumably, this environment has to be listed in the Trusted Publisher settings, right?

**Comment by IAlibay** [comment]
> Does this now run in a _deploy_ environment?
> 
> Do we have to configure this environment in the repo settings? Presumably, this environment has to be listed in the Trusted Publisher settings, right?

`deploy` already exists and I believe I set up the trusted settings with the env name.

**Comment by IAlibay** [comment]
We do need to delete out the token secrets in the `deploy` environment though.

**Comment by orbeckst** [comment]
I just removed the two tokens from "deploy".

**Comment by orbeckst** [comment]
Have to dash... will continue on MDAnalysisData later tonight.

**Pull request merged**
