### PR TITLE
Bump to miniforge and py3.13

### PR DESCRIPTION
**Pull request by IAlibay**

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
I assume that the failures on 3.13 are because we do not have MDAnalysis at 3.13 yet?

Everything looks good in principle so I approve.

Thank you for the comprehensive update.

**Comment by orbeckst** [comment]
@IAlibay please merge at will.

**Comment by IAlibay** [comment]
> I assume that the failures on 3.13 are because we do not have MDAnalysis at 3.13 yet?

no.. it should be the other way around (griddataformats is a dependency of MDA) - I'll need to look at that more.

**Comment by IAlibay** [comment]
I think I remember this bug being that conda isn't aliased to micromamba for non-linux cases. Hopefully this fixes it.

**Comment by IAlibay** [comment]
Here we go, that does the trick - thanks for the review @orbeckst !

**Pull request merged**
