### PR TITLE
This should container builds in travis-CI

### PR DESCRIPTION
**Pull request by kain88-de**
lets see if this works

### CODE REVIEW

**Comment by orbeckst** [comment]
I thought container builds are the default nowadays, and you'd only get something different with `sudo: True`.

**Comment by kain88-de** [comment]
I got a message about using the old infrastructure on the travis build. The docs say that they are only explicitly activated with the sudo flag

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by orbeckst** [comment]
Hi Max,

> I got a message about using the old infrastructure on the travis build. The docs say that they are only explicitly activated with the sudo flag

Then I obviously mis-remembered. I thought that MDAnalysis runs on the new containers even though the sudo=false is flag is not set. At least that's what I remember from conversations with @richardjgowers and checking the log such as https://travis-ci.org/MDAnalysis/mdanalysis/builds/80046564 says that it is using docker and containers:

 Using worker: worker-linux-docker-bf8ff456.prod.travis-ci.org:travis-linux-3

 This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
 If you require sudo, add 'sudo: required' to your .travis.yml 
 See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Cheers,
Oliver

**Comment by richardjgowers** [comment]
@orbeckst you're not wrong, MDAnalysis defaulted to container based once we got rid of sudo.  I'm not sure why this didn't too, but it's fixed now

**Pull request merged**
